Resources:

  # S3 bucket for storing the website
  WebsiteBucket:
    Type: 'AWS::S3::Bucket'

  # S3 bucket for storing the tiles
  TileBucket:
    Type: 'AWS::S3::Bucket'

  # S3 bucket policy for the CloudFront origin access identity
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal:
              AWS: !Join [' ', ['arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity', !Ref CloudFrontOriginAccessIdentity]]
            Action:
              - s3:GetObject
            Resource:
              - !Sub 'arn:aws:s3:::${WebsiteBucket}/*'
