service: serverlessmaps

frameworkVersion: '3'

plugins:
  - serverless-iam-roles-per-function
  - serverless-esbuild
  - serverless-stack-output
  - serverless-s3-sync

custom:

  cors:
    allowedDomain: ${opt:cors, '*'}

  # Prune plugin
  prune:
    automatic: true
    number: 3

  # esbuild plugin
  esbuild:
    bundle: true
    minify: false
    exclude:
      - '@aws-sdk/client-s3'
      - '@aws-sdk/node-http-handler'

  # Output plugin (for writing the CloudFront Distribution URLs to the website config)
  output:
    handler: scripts/output.handler
    file: scripts/outputs.json

  # S3 sync plugin configuration
  s3Sync:
    - bucketNameKey: TileBucketName
      localDir: ../data/tiles
    - bucketNameKey: WebsiteBucketName
      localDir: ../website

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'prd'}
  logRetentionInDays: 7
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1' # Enable HTTP keep-alive connections for the AWS SDK
    STAGE: '${self:provider.stage}'
    LOG_LEVEL: 'debug'

functions:
  pmTilesProxy:
    handler: functions/pmTilesProxy.handler
    architecture: arm64
    memorySize: 512
    timeout: 15
    url: true
    # See https://protomaps.com/docs/cdn/aws#configuration
    environment:
      BUCKET: !Ref TileBucket
      CORS: '${self:custom.cors.allowedDomain}'
      # Can only be use with a real domain
      # PUBLIC_HOSTNAME: !GetAtt 'TilesDistribution.DomainName'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource: !Sub 'arn:aws:s3:::${TileBucket}/*'

resources:

  - ${file(resources/s3-buckets.yml)}
  - ${file(resources/cf-distribution.yml)}
  - ${file(resources/outputs.yml)}

package:
  individually: true
